git:
  submodules: false
language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    emulator/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

env:
  matrix:
    - SUITE=RocketSuiteA
    - SUITE=RocketSuiteB
    - SUITE=GroundtestSuiteA
    - SUITE=GroundtestSuiteB
    - SUITE=UnittestSuite

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - /^hurricane.*$/

install:
  - make tools verilator -C regression SUITE=none

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

script:
  - make emulator-ndebug -C regression SUITE=$SUITE TORTURE_CONFIG=default
  - make emulator-regression-tests -C regression SUITE=$SUITE TORTURE_CONFIG=default

before_cache:
  - ls -t regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
